## This R script is run by cmake.
## It takes the SimpleITK.R file generated by swig and splits it into
## two parts. The small part contains all the calls to
## defineEnumeration, some of which won't work unless the
## shared library is available. These calls are placed in
## the package's .onLoad function.
##
## The second file contains all the rest, and is written in to the
## package R directory

# arguments after --args
arguments <- commandArgs( TRUE )

swigfile <- arguments[1]
destdir <- arguments[2]


## This function uses the R language parsing capabilities.
## We're looking for calls to defineEnumeration...

splitSwigFile <- function(filename, onloadfile, mainfile)
{
  p1 <- parse(file=filename)

  getdefineEnum <- function(X)
  {
    return (is.call(X) & (X[[1]]=="defineEnumeration"))
  }

  dd <- sapply(p1, getdefineEnum)

  enums <- p1[dd]
  enums <- unlist(lapply(enums, deparse))

  ## put the function def around this
  enums <- c(".onLoad <- function(libname, pkgname) {", enums, "}")

  everythingelse <- p1[!dd]
  everythingelse <- unlist(lapply(everythingelse, deparse))
  writeLines(everythingelse, mainfile)
  writeLines(enums, onloadfile)

}

mainfile <- file.path(destdir, "SimpleITK.R")
onloadfile <- file.path(destdir, "zonload.R")

print(mainfile)
print(onloadfile)
splitSwigFile(swigfile, onloadfile, mainfile)
